-- ============================================================
-- QUALIFIED PROVEEDORES — SGA (gestión de almacén) · Fase 1 · Paso 1: tablas
--
-- Idea central: el stock NO se guarda como un número que se edita. Se guarda cada
-- movimiento (libro de movimientos) y el stock sale de sumarlos. Nada se borra: un
-- albarán equivocado se ANULA y el stock vuelve solo a como estaba.
--
--   sga_zonas / sga_ubicaciones   Dónde se guarda: almacén → (nave) → zona → ubicación (solo estanterías)
--   sga_clientes                  Ajustes del SGA por cliente (desde cuándo se cobra, códigos únicos, campos)
--   sga_albaranes                 Cada entrada, salida o apertura (stock inicial) con su cabecera
--   sga_partidas                  La unidad de stock: N palets iguales, o 1 palet con código
--   sga_movimientos               El libro: cada entrada (+) o salida (−) de cada partida
--   sga_servicios                 Horas y extras anotados en un albarán (hora operario, retractilado…)
--   sga_cobros                    Lo que se cobra por cada movimiento, con el precio congelado del día
--
-- Permisos: ver y operar = módulo «stock» (se añade en Gestión de permisos);
-- zonas, ubicaciones y ajustes por cliente = «almacenconfig». Administradores: todo.
-- Instrucciones: Supabase → SQL Editor → pega esto ENTERO → Run.
-- ============================================================

-- Comprobación de permisos (admin o alguna de las pestañas indicadas)
create or replace function public.sga_permiso(variadic tabs text[]) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and (p.is_admin or p.allowed_tabs ?| tabs)
  );
$$;

-- ---------- Zonas y ubicaciones ----------
create table if not exists public.sga_zonas (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  warehouse_id text not null references public.warehouses(id),
  nave text,                                   -- opcional: p. ej. «Nave 2» en Pirelli Manresa
  nombre text not null,
  tipo text not null default 'suelo' check (tipo in ('suelo', 'estanteria')),
  orden integer not null default 0,
  archived boolean not null default false
);
create unique index if not exists sga_zonas_unica on public.sga_zonas (warehouse_id, coalesce(lower(nave), ''), lower(nombre));

create table if not exists public.sga_ubicaciones (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  zona_id uuid not null references public.sga_zonas(id),
  codigo text not null,                        -- p. ej. A-03-2 (pasillo, columna, nivel)
  archived boolean not null default false
);
create unique index if not exists sga_ubicaciones_unica on public.sga_ubicaciones (zona_id, lower(codigo));

-- ---------- Ajustes del SGA por cliente ----------
create table if not exists public.sga_clientes (
  cliente_id uuid primary key references public.contactos(id),
  updated_at timestamptz not null default now(),
  activo_desde date,                           -- hasta esta fecha el SGA no cobra a este cliente (sigue en el Excel)
  codigos_unicos boolean not null default false,  -- true: cada palet lleva su código (partida de 1)
  campos jsonb not null default '{"referencia":"opcional","descripcion":"opcional","lote":"no"}'::jsonb,
  observaciones text
);

-- ---------- Albaranes ----------
create table if not exists public.sga_albaranes (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  created_at timestamptz not null default now(),
  created_by text,
  tipo text not null check (tipo in ('entrada', 'salida', 'apertura')),
  cliente_id uuid not null references public.contactos(id),
  warehouse_id text not null references public.warehouses(id),
  fecha date not null,
  referencia text,                             -- referencia / nº de albarán del cliente o transportista
  modalidad text not null default 'palet' check (modalidad in ('palet', 'contenedor_20', 'contenedor_40', 'trailer')),
  transportista text,
  matricula text,
  observaciones text,
  estado text not null default 'borrador' check (estado in ('borrador', 'confirmado', 'anulado')),
  confirmado_at timestamptz,
  anulado_at timestamptz,
  anulado_motivo text
);
create index if not exists sga_albaranes_cliente_idx on public.sga_albaranes (cliente_id, fecha);

-- ---------- Partidas (la unidad de stock) ----------
create table if not exists public.sga_partidas (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  cliente_id uuid not null references public.contactos(id),
  warehouse_id text not null references public.warehouses(id),
  zona_id uuid references public.sga_zonas(id),
  ubicacion_id uuid references public.sga_ubicaciones(id),
  producto_id text not null references public.almacenaje_productos(id),  -- tipo de carga: Palet Europeo, Bobina D.20…
  referencia text,
  descripcion text,
  lote text,
  codigo text,                                 -- código único del palet (solo clientes con códigos únicos)
  cantidad_inicial integer not null check (cantidad_inicial > 0),
  cantidad_actual integer not null check (cantidad_actual >= 0),
  fecha_entrada date not null,                 -- base del FIFO
  albaran_entrada_id uuid references public.sga_albaranes(id),
  atributos jsonb not null default '{}'::jsonb,  -- campos propios de cada cliente (caducidad, peso…)
  estado text not null default 'activa' check (estado in ('activa', 'agotada', 'anulada'))
);
create unique index if not exists sga_partidas_codigo_unico on public.sga_partidas (cliente_id, lower(codigo)) where codigo is not null;
create index if not exists sga_partidas_stock_idx on public.sga_partidas (cliente_id, estado, fecha_entrada);

-- ---------- Libro de movimientos ----------
create table if not exists public.sga_movimientos (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  created_by text,
  partida_id uuid not null references public.sga_partidas(id),
  albaran_id uuid references public.sga_albaranes(id),
  tipo text not null check (tipo in ('entrada', 'salida', 'apertura', 'ajuste', 'traslado')),
  cantidad integer not null check (cantidad <> 0),   -- + entra, − sale
  fecha date not null,
  fifo_saltado boolean not null default false,        -- true si en una salida no se siguió el FIFO
  nota text
);
create index if not exists sga_movimientos_partida_idx on public.sga_movimientos (partida_id);
create index if not exists sga_movimientos_albaran_idx on public.sga_movimientos (albaran_id);

-- ---------- Servicios anotados en un albarán ----------
create table if not exists public.sga_servicios (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  albaran_id uuid not null references public.sga_albaranes(id),
  producto_id text not null references public.almacenaje_productos(id),
  cantidad numeric(12,2) not null check (cantidad > 0),
  nota text
);

-- ---------- Cobros calculados ----------
create table if not exists public.sga_cobros (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  cliente_id uuid not null references public.contactos(id),
  albaran_id uuid references public.sga_albaranes(id),
  fecha date not null,
  periodo text not null,                       -- 'AAAA-MM'
  origen text not null check (origen in ('movimiento', 'servicio', 'stock_dia', 'stock_max_mes', 'manual')),
  producto_id text not null references public.almacenaje_productos(id),
  subtipo text,
  cantidad numeric(12,2) not null,
  precio numeric not null,                     -- precio congelado en el momento del cobro
  importe numeric(12,2) not null,
  tarifa_id uuid references public.almacenaje_tarifas(id),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'revisado', 'facturado', 'anulado')),
  nota text
);
create index if not exists sga_cobros_cliente_idx on public.sga_cobros (cliente_id, periodo);

-- ============================================================
-- Seguridad (RLS)
-- ============================================================
alter table public.sga_zonas enable row level security;
alter table public.sga_ubicaciones enable row level security;
alter table public.sga_clientes enable row level security;
alter table public.sga_albaranes enable row level security;
alter table public.sga_partidas enable row level security;
alter table public.sga_movimientos enable row level security;
alter table public.sga_servicios enable row level security;
alter table public.sga_cobros enable row level security;

-- Configuración: verla quien opera el SGA o la configuración de almacenes; cambiarla, solo configuración.
do $$
declare t text;
begin
  foreach t in array array['sga_zonas', 'sga_ubicaciones', 'sga_clientes'] loop
    execute format('drop policy if exists %1$s_select on public.%1$s', t);
    execute format('drop policy if exists %1$s_insert on public.%1$s', t);
    execute format('drop policy if exists %1$s_update on public.%1$s', t);
    execute format('create policy %1$s_select on public.%1$s for select using (public.sga_permiso(''stock'', ''almacenconfig'', ''citas''))', t);
    execute format('create policy %1$s_insert on public.%1$s for insert with check (public.sga_permiso(''almacenconfig''))', t);
    execute format('create policy %1$s_update on public.%1$s for update using (public.sga_permiso(''almacenconfig''))', t);
  end loop;
end $$;

-- Operativa: quien tiene el módulo «stock». No hay política de borrado: nada se borra, se anula.
do $$
declare t text;
begin
  foreach t in array array['sga_albaranes', 'sga_partidas', 'sga_movimientos', 'sga_servicios', 'sga_cobros'] loop
    execute format('drop policy if exists %1$s_select on public.%1$s', t);
    execute format('drop policy if exists %1$s_insert on public.%1$s', t);
    execute format('drop policy if exists %1$s_update on public.%1$s', t);
    execute format('create policy %1$s_select on public.%1$s for select using (public.sga_permiso(''stock''))', t);
    execute format('create policy %1$s_insert on public.%1$s for insert with check (public.sga_permiso(''stock''))', t);
    execute format('create policy %1$s_update on public.%1$s for update using (public.sga_permiso(''stock''))', t);
  end loop;
end $$;

notify pgrst, 'reload schema';

-- Para comprobar que se ha creado todo (deben salir 8 filas):
-- select table_name from information_schema.tables where table_schema = 'public' and table_name like 'sga\_%' order by 1;
